// City data for /we-buy-houses/[city] pages.
// Population and zip codes are sourced from the 2020 U.S. Census / USPS ZIP
// data (public, verifiable facts) - not invented. Descriptions are written
// in-house, not copied from any competitor. What's deliberately NOT here:
// fake testimonials, fake "we've bought X houses in this city" claims, or
// fabricated local proof - that gets added for real once a case study exists
// (see /projects), per lib/situations.ts's note on the same rule.

export type CityData = {
  slug: string;
  name: string;
  county: string;
  zipCodes: string[];
  neighborhoods: string[];
  population: string;
  description: string;
  marketNote: string; // one real, sourced fact about the local housing market
  quickFacts: string[]; // 5 short, real, locally-relevant facts
  featured?: boolean; // top 12 by population, used to trim the nav dropdown/menu
};

export const cities: CityData[] = [
  {
    slug: "visalia",
    featured: true,
    name: "Visalia",
    county: "Tulare County",
    zipCodes: ["93277", "93291", "93292"],
    neighborhoods: ["Downtown Visalia", "North Visalia", "Mooney", "Cottage Grove"],
    population: "141,000",
    description:
      "We buy houses fast for cash in Visalia, CA. From downtown to north Visalia, we purchase properties in any condition and close on your timeline.",
    marketNote:
      "Visalia is the county seat of Tulare County and the largest city House Junkies operates in, with a housing stock that spans historic downtown homes to newer construction on the north side.",
    quickFacts: [
      "Visalia is often called the gateway to Sequoia and Kings Canyon National Parks, about a 45-minute drive from downtown.",
      "Downtown Visalia is home to the restored 1930s Visalia Fox Theatre and a walkable historic Main Street district.",
      "Mooney Grove Park and the Rawhide Ballpark (home of the Visalia Rawhide minor league team) are two of the city's most-visited spots.",
      "Visalia has more Valley Oak trees than any other city in California's San Joaquin Valley.",
      "As the Tulare County seat, Visalia is the administrative and economic hub for the surrounding smaller cities.",
    ],
  },
  {
    slug: "tulare",
    featured: true,
    name: "Tulare",
    county: "Tulare County",
    zipCodes: ["93274", "93261"],
    neighborhoods: ["Downtown Tulare", "North Tulare", "South Tulare"],
    population: "70,000",
    description:
      "Sell your Tulare house fast for cash. We buy homes as-is throughout Tulare, no repairs, no fees, no hassle.",
    marketNote:
      "Tulare sits just south of Visalia along Highway 99 and has a strong base of older, established housing stock alongside newer subdivisions.",
    quickFacts: [
      "Tulare hosts the World Ag Expo every February at the International Agri-Center, one of the largest annual outdoor agricultural expositions in the world.",
      "Tulare County is consistently ranked among the top agricultural-producing counties in the entire country.",
      "The city's historic downtown includes tree-lined streets, murals, and the Tulare Historical Museum.",
      "Tulare sits along Highway 99, roughly midway between Fresno and Bakersfield.",
      "The Tulare Outlet Center draws shoppers from across the surrounding smaller Tulare County cities.",
    ],
  },
  {
    slug: "porterville",
    featured: true,
    name: "Porterville",
    county: "Tulare County",
    zipCodes: ["93257", "93258"],
    neighborhoods: ["Downtown Porterville", "West Porterville", "East Porterville"],
    population: "63,000",
    description:
      "Get a fair cash offer for your Porterville home. We buy houses in any condition and close on your timeline.",
    marketNote:
      "Porterville is the largest city in Tulare County's east side, closer to the Sierra foothills, with a mix of agricultural-adjacent properties and in-town housing.",
    quickFacts: [
      "Porterville sits closer to the Sierra Nevada foothills than Visalia or Tulare, making it a gateway to Sequoia National Forest.",
      "It's the largest city on the east side of Tulare County.",
      "The Zalud House, a preserved Victorian-era home, is one of the city's notable historic landmarks.",
      "Porterville's economy leans heavily on citrus and other agriculture, similar to much of the county.",
      "The Tule River runs through the city, feeding into Lake Success just east of town.",
    ],
  },
  {
    slug: "fresno",
    featured: true,
    name: "Fresno",
    county: "Fresno County",
    zipCodes: ["93701", "93702", "93703", "93704", "93705", "93710", "93711"],
    neighborhoods: ["Downtown Fresno", "Tower District", "Fig Garden", "North Fresno", "Woodward Park"],
    population: "545,000",
    description:
      "Sell your Fresno house fast for cash. We buy homes as-is throughout Fresno County, from Tower District to North Fresno.",
    marketNote:
      "Fresno is the largest city in the Central Valley and the anchor of the region's housing market, with everything from century-old Tower District bungalows to newer north Fresno development.",
    quickFacts: [
      "Fresno is the largest city in the Central Valley and the fifth-largest in California.",
      "The Tower District is Fresno's historic entertainment and arts neighborhood, built around the 1930s Tower Theatre.",
      "Fresno State (California State University, Fresno) is a major anchor for the city's northeast side.",
      "Woodward Park, one of the largest parks in Fresno, includes the Shinzen Japanese Garden.",
      "Fresno sits at the crossroads of Highway 99 and Highway 41, making it the transportation hub of the Valley.",
    ],
  },
  {
    slug: "dinuba",
    name: "Dinuba",
    county: "Tulare County",
    zipCodes: ["93618"],
    neighborhoods: ["Downtown Dinuba", "Alta District"],
    population: "24,563",
    description:
      "We buy houses fast for cash in Dinuba, CA. As-is, any condition, no fees, no repairs.",
    marketNote:
      "Dinuba, nicknamed \"Raisin City\" for its agricultural roots, is one of Tulare County's larger cities by population, incorporated in 1906 with a housing stock that reflects that long history.",
    quickFacts: [
      "Dinuba is nicknamed \"Raisin City\" for its long agricultural history in raisin and grape production.",
      "The city was incorporated in 1906 and has kept a historic downtown core from that era.",
      "The Alta District Museum, housed in a restored railroad station, covers Dinuba's local history.",
      "Dinuba sits along Highway 201, connecting it to both Visalia and Reedley.",
      "Agriculture and food processing remain the backbone of the local economy.",
    ],
  },
  {
    slug: "bakersfield",
    featured: true,
    name: "Bakersfield",
    county: "Kern County",
    zipCodes: ["93301", "93304", "93305", "93306", "93307", "93309", "93311", "93312", "93313", "93314"],
    neighborhoods: ["Downtown Bakersfield", "Southwest Bakersfield", "Northeast Bakersfield", "Oleander"],
    population: "400,000+",
    description:
      "We buy houses fast for cash in Bakersfield, CA. As-is, any condition, no fees, no repairs.",
    marketNote:
      "Bakersfield is the ninth-largest city in California and the seat of Kern County, with a large enough footprint that it spans over a dozen ZIP codes and housing stock ranging from historic downtown properties to large newer subdivisions in the southwest.",
    quickFacts: [
      "Bakersfield is the ninth-largest city in California and the seat of Kern County.",
      "The city is closely associated with country music history as the birthplace of the \"Bakersfield Sound,\" made famous by Buck Owens and Merle Haggard.",
      "Kern County is one of the top oil-producing counties in the country, and oil remains a major part of Bakersfield's economy alongside agriculture.",
      "Downtown Bakersfield has been undergoing a revitalization push in recent years, adding restaurants and mixed-use development.",
      "Bakersfield sits at the southern end of the San Joaquin Valley, about an hour and a half south of Visalia.",
    ],
  },
  {
    slug: "exeter",
    name: "Exeter",
    county: "Tulare County",
    zipCodes: ["93221"],
    neighborhoods: ["Downtown Exeter"],
    population: "10,321",
    description:
      "We buy houses fast for cash in Exeter, CA. As-is, any condition, no fees, no repairs.",
    marketNote:
      "Exeter sits in the foothills of the Sierra Nevada east of Visalia, known locally for its historic downtown murals and a smaller, tighter-knit housing market than the larger Valley cities.",
    quickFacts: [
      "Exeter is known locally for its collection of large outdoor murals depicting the area's agricultural history, spread throughout downtown.",
      "The city sits in the foothills east of Visalia, closer to the Sierra Nevada than most other Tulare County cities.",
      "Exeter was incorporated in 1911 and has kept a small, historic downtown core.",
      "Citrus growing has historically been central to Exeter's economy, given its foothill location.",
      "The city is small enough that most of its housing stock is within a few minutes of downtown.",
    ],
  },
  {
    slug: "farmersville",
    name: "Farmersville",
    county: "Tulare County",
    zipCodes: ["93223"],
    neighborhoods: ["Downtown Farmersville"],
    population: "10,397",
    description:
      "We buy houses fast for cash in Farmersville, CA. As-is, any condition, no fees, no repairs.",
    marketNote:
      "Farmersville is a small city bordering Visalia on the east side of Tulare County, incorporated in 1960, with one of the more affordable housing markets in the county.",
    quickFacts: [
      "Farmersville was incorporated in 1960 and borders Visalia directly on the east side of Tulare County.",
      "The city's economy is closely tied to agriculture, consistent with much of the surrounding area.",
      "Farmersville is one of the more affordable housing markets in Tulare County.",
      "Its small size means most residents rely on nearby Visalia for larger shopping and services.",
      "The median age in Farmersville skews younger than the county overall.",
    ],
  },
  {
    slug: "goshen",
    name: "Goshen",
    county: "Tulare County",
    zipCodes: ["93227"],
    neighborhoods: ["Goshen"],
    population: "4,968",
    description:
      "We buy houses fast for cash in Goshen, CA. As-is, any condition, no fees, no repairs.",
    marketNote:
      "Goshen is an unincorporated community about five miles west of Visalia. Tulare County is currently working on a Goshen Community Plan update, which points to real growth and change coming to the area.",
    quickFacts: [
      "Goshen is an unincorporated community about five miles west of Visalia, governed directly by Tulare County rather than its own city government.",
      "Tulare County is currently working on a Goshen Community Plan update, which points to real growth and change coming to the area.",
      "Goshen sits along Highway 99, making it a logistics and industrial corridor for the wider Visalia area.",
      "Because it's unincorporated, some services and permitting in Goshen route through the county rather than a city hall.",
      "Goshen is one of the smallest communities House Junkies serves by population.",
    ],
  },
  {
    slug: "hanford",
    featured: true,
    name: "Hanford",
    county: "Kings County",
    zipCodes: ["93230"],
    neighborhoods: ["Downtown Hanford", "China Alley"],
    population: "57,000",
    description:
      "We buy houses fast for cash in Hanford, CA. As-is, any condition, no fees, no repairs.",
    marketNote:
      "Hanford is the county seat of Kings County and the largest city in the Hanford-Corcoran area, with a historic downtown (China Alley, the Fox Theatre) and a housing market that mixes century-old homes with newer growth on the city's edges.",
    quickFacts: [
      "Hanford is the seat of Kings County and the largest city in the Hanford-Corcoran area.",
      "Its historic China Alley district, dating to the 1800s, includes the Taoist Temple, one of the oldest Chinese temples in California.",
      "The restored Hanford Fox Theatre anchors the city's historic downtown.",
      "Hanford's Courthouse Square, built around the old Kings County Courthouse, is the center of downtown dining and events.",
      "Agriculture and dairy remain major parts of the Kings County economy surrounding Hanford.",
    ],
  },
  {
    slug: "lemoore",
    featured: true,
    name: "Lemoore",
    county: "Kings County",
    zipCodes: ["93245", "93246"],
    neighborhoods: ["Downtown Lemoore"],
    population: "27,057",
    description: "We buy houses fast for cash in Lemoore, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Lemoore is home to Naval Air Station Lemoore, a major Navy jet base that anchors a meaningful share of the local economy and housing demand.",
    quickFacts: [
      "Lemoore was incorporated in 1900 and sits about 7 miles west-southwest of Hanford.",
      "Naval Air Station Lemoore, a master jet base for Pacific Fleet F-18 and F-35 squadrons, is one of the largest employers in the area.",
      "The city is part of the Hanford-Corcoran Metropolitan Statistical Area.",
      "Lemoore's population has grown steadily, roughly doubling since the 1990 Census.",
      "Agriculture and the naval base together make up the backbone of the local economy.",
    ],
  },
  {
    slug: "corcoran",
    name: "Corcoran",
    county: "Kings County",
    zipCodes: ["93212"],
    neighborhoods: ["Downtown Corcoran"],
    population: "22,627",
    description: "We buy houses fast for cash in Corcoran, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Corcoran is served by Amtrak, one of the few smaller Central Valley cities with a direct passenger rail stop.",
    quickFacts: [
      "Corcoran sits in western Kings County, in the heart of cotton and row-crop farm country.",
      "The city is home to two California state prisons, which are major local employers.",
      "Amtrak trains stop directly in Corcoran, unusual for a city this size.",
      "Corcoran's population has grown significantly since 1990, more than doubling.",
      "The local economy leans heavily on agriculture and correctional-facility employment.",
    ],
  },
  {
    slug: "avenal",
    name: "Avenal",
    county: "Kings County",
    zipCodes: ["93204"],
    neighborhoods: ["Downtown Avenal"],
    population: "14,108",
    description: "We buy houses fast for cash in Avenal, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Avenal sits at the western edge of Kings County, closer to the Coast Ranges than to the rest of the Central Valley cities House Junkies serves.",
    quickFacts: [
      "Avenal is home to Avenal State Prison, one of the city's largest employers.",
      "The city has a privately-owned airport that's home to the Central California Soaring Club.",
      "Avenal is the westernmost city House Junkies serves in Kings County.",
      "Oil and gas extraction historically played a role in the area's economy alongside agriculture.",
      "The city's housing stock is smaller and more affordable than the Kings County average.",
    ],
  },
  {
    slug: "clovis",
    featured: true,
    name: "Clovis",
    county: "Fresno County",
    zipCodes: ["93611", "93612", "93619"],
    neighborhoods: ["Old Town Clovis", "Loma Vista", "Harlan Ranch"],
    population: "111,990",
    description: "We buy houses fast for cash in Clovis, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Clovis is one of the fastest-growing cities in Fresno County, with new development pushing east and north of Old Town.",
    quickFacts: [
      "Clovis is directly adjacent to Fresno and is part of the greater Fresno-Clovis metro area.",
      "Old Town Clovis retains a historic downtown core with its own distinct identity from the newer subdivisions.",
      "Clovis has grown from roughly 108,000 to over 111,000 in the last decade, among the fastest growth rates in the county.",
      "The city is known locally for a strong public school district that drives a lot of family relocation demand.",
      "Clovis sits just east of Fresno along Highway 168, at the edge of the Sierra Nevada foothills.",
    ],
  },
  {
    slug: "sanger",
    featured: true,
    name: "Sanger",
    county: "Fresno County",
    zipCodes: ["93657"],
    neighborhoods: ["Downtown Sanger"],
    population: "26,784",
    description: "We buy houses fast for cash in Sanger, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Sanger calls itself the \"Christmas Tree Lane City\" and sits along the route many Fresno-area residents take toward Kings Canyon National Park.",
    quickFacts: [
      "Sanger is located about 15 miles east of Fresno, closer to the Sierra Nevada foothills.",
      "The city's economy is closely tied to fruit and nut agriculture, packing, and processing.",
      "Sanger has grown from about 16,800 residents in 1990 to nearly 27,000 today.",
      "It sits along the route toward Kings Canyon and Sequoia National Parks from the Fresno area.",
      "Sanger has its own school district and a small, walkable historic downtown.",
    ],
  },
  {
    slug: "selma",
    name: "Selma",
    county: "Fresno County",
    zipCodes: ["93662"],
    neighborhoods: ["Downtown Selma"],
    population: "24,773",
    description: "We buy houses fast for cash in Selma, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Selma calls itself the \"Raisin Capital of the World,\" reflecting the same raisin-and-grape agricultural heritage as Dinuba just south of it.",
    quickFacts: [
      "Selma sits along Highway 99 between Fresno and Fowler, in the heart of Fresno County's grape-growing region.",
      "The city has long branded itself around raisin production, similar to Dinuba to the south.",
      "Selma's population has grown from about 15,200 in 1990 to nearly 25,000.",
      "Agriculture, packing, and food processing remain central to the local economy.",
      "Selma is a short drive from both Fresno and the smaller Fresno County cities to its south.",
    ],
  },
  {
    slug: "reedley",
    name: "Reedley",
    county: "Fresno County",
    zipCodes: ["93654"],
    neighborhoods: ["Downtown Reedley"],
    population: "25,193",
    description: "We buy houses fast for cash in Reedley, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Reedley sits along the Kings River and is home to Reedley College, a community college serving the surrounding farm towns.",
    quickFacts: [
      "Reedley is situated on the Kings River in southeastern Fresno County.",
      "Reedley College serves as an educational anchor for the surrounding smaller agricultural communities.",
      "The city's population has grown from about 16,000 in 1990 to over 25,000.",
      "Fruit farming, particularly stone fruit and citrus, is central to Reedley's economy.",
      "Reedley calls itself the \"World's Fruit Basket\" for its concentration of orchards.",
    ],
  },
  {
    slug: "delano",
    featured: true,
    name: "Delano",
    county: "Kern County",
    zipCodes: ["93215"],
    neighborhoods: ["Downtown Delano"],
    population: "51,420",
    description: "We buy houses fast for cash in Delano, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Delano is the second-largest city in Kern County and is historically significant as the birthplace of the United Farm Workers movement.",
    quickFacts: [
      "Delano is the northernmost city in Kern County and the second-largest by population.",
      "The city holds historical significance as the starting point of the United Farm Workers movement led by Cesar Chavez and Dolores Huerta.",
      "Table grapes and other row-crop agriculture remain central to the local economy.",
      "Delano sits along Highway 99, providing straightforward access to both Bakersfield and the Tulare County cities to the north.",
      "The city has two state prisons that are significant local employers.",
    ],
  },
  {
    slug: "ridgecrest",
    featured: true,
    name: "Ridgecrest",
    county: "Kern County",
    zipCodes: ["93555"],
    neighborhoods: ["Downtown Ridgecrest"],
    population: "27,960",
    description: "We buy houses fast for cash in Ridgecrest, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Ridgecrest sits at the eastern edge of Kern County in the Mojave Desert, far closer to the Naval Air Weapons Station China Lake than to the rest of Kern County's Central Valley cities.",
    quickFacts: [
      "Ridgecrest is in the Mojave Desert portion of Kern County, geographically distinct from the Central Valley cities House Junkies primarily serves.",
      "The city's economy is closely tied to the Naval Air Weapons Station at China Lake.",
      "Ridgecrest is Kern County's easternmost significant population center.",
      "The city sits along Highway 395, a major corridor for travel between the Central Valley and the eastern Sierra.",
      "Housing demand in Ridgecrest is closely tied to military personnel turnover at the nearby base.",
    ],
  },
  {
    slug: "wasco",
    featured: true,
    name: "Wasco",
    county: "Kern County",
    zipCodes: ["93280"],
    neighborhoods: ["Downtown Wasco"],
    population: "27,049",
    description: "We buy houses fast for cash in Wasco, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Wasco calls itself the \"Rose Capital of the Nation\" for its concentration of rose-growing nurseries.",
    quickFacts: [
      "Wasco sits along Highway 46 in northwestern Kern County, a short drive from Bakersfield.",
      "The city is known for rose cultivation, alongside broader row-crop and almond agriculture.",
      "Wasco's population has more than doubled since 1990.",
      "A state prison in Wasco is a significant local employer alongside agriculture.",
      "The city is one of the smaller, more affordable housing markets in Kern County.",
    ],
  },
  {
    slug: "shafter",
    name: "Shafter",
    county: "Kern County",
    zipCodes: ["93263"],
    neighborhoods: ["Downtown Shafter"],
    population: "19,956",
    description: "We buy houses fast for cash in Shafter, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Shafter has been one of the fastest-growing cities in Kern County in recent years, driven by new housing development and logistics/warehouse growth.",
    quickFacts: [
      "Shafter sits just northwest of Bakersfield along Highway 43.",
      "The city has seen some of the fastest population growth in Kern County recently, gaining over 4 percent in a single recent year per state estimates.",
      "Agriculture and a growing logistics/distribution sector both drive the local economy.",
      "Shafter is close enough to Bakersfield to serve as a bedroom community for some residents.",
      "New housing development has been a bigger factor in Shafter's growth than in most other small Kern County cities.",
    ],
  },
  {
    slug: "lindsay",
    name: "Lindsay",
    county: "Tulare County",
    zipCodes: ["93247"],
    neighborhoods: ["Downtown Lindsay"],
    population: "13,247",
    description: "We buy houses fast for cash in Lindsay, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Lindsay calls itself the \"Olive Capital of the World\" and is home to one of the largest olive processing operations in the country.",
    quickFacts: [
      "Lindsay sits along Highway 65 in eastern Tulare County, at the foot of the Sierra Nevada foothills.",
      "The city's economy is built around olive and citrus agriculture, home to major olive oil and canning operations.",
      "Lindsay has a small, historic downtown with a number of early-1900s brick commercial buildings.",
      "The city is about a 20 minute drive from Visalia and a similar distance from Porterville.",
      "Lindsay's population has grown modestly over the past two decades, staying centered on agricultural employment.",
    ],
  },
  {
    slug: "woodlake",
    name: "Woodlake",
    county: "Tulare County",
    zipCodes: ["93286"],
    neighborhoods: ["Downtown Woodlake"],
    population: "7,800",
    description: "We buy houses fast for cash in Woodlake, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Woodlake sits at the foothills gateway toward Sequoia National Park, closer to the mountains than most other Tulare County cities House Junkies serves.",
    quickFacts: [
      "Woodlake is one of the closest incorporated cities to the entrance of Sequoia National Park.",
      "The city is built around citrus, olive, and other foothill agriculture.",
      "Woodlake is a small, close-knit community with a historic downtown core.",
      "The Kaweah River runs near Woodlake on its way down from the Sierra Nevada.",
      "Woodlake is about a 25 minute drive northeast of Visalia.",
    ],
  },
  {
    slug: "earlimart",
    name: "Earlimart",
    county: "Tulare County",
    zipCodes: ["93219"],
    neighborhoods: ["Downtown Earlimart"],
    population: "7,679",
    description: "We buy houses fast for cash in Earlimart, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Earlimart sits along Highway 99 in southern Tulare County, in an area historically significant to the farmworker labor movement.",
    quickFacts: [
      "Earlimart is an unincorporated community in southern Tulare County, along Highway 99.",
      "The area's economy is built on row-crop and tree-fruit agriculture.",
      "Earlimart is near Delano, another Central Valley city with deep United Farm Workers history.",
      "The community is served by its own elementary school district.",
      "Earlimart sits roughly halfway between Tulare and Delano along the Highway 99 corridor.",
    ],
  },
  {
    slug: "strathmore",
    name: "Strathmore",
    county: "Tulare County",
    zipCodes: ["93267"],
    neighborhoods: ["Downtown Strathmore"],
    population: "2,830",
    description: "We buy houses fast for cash in Strathmore, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Strathmore is a small citrus-growing community between Lindsay and Porterville in eastern Tulare County.",
    quickFacts: [
      "Strathmore is an unincorporated community in Tulare County, between Lindsay and Porterville.",
      "The local economy is almost entirely built on citrus packing and agriculture.",
      "Strathmore is close to the base of the Sierra Nevada foothills.",
      "The community has its own elementary school serving the surrounding farm area.",
      "Strathmore sits just off Highway 65, the main foothill corridor through eastern Tulare County.",
    ],
  },
  {
    slug: "springville",
    name: "Springville",
    county: "Tulare County",
    zipCodes: ["93265"],
    neighborhoods: ["Downtown Springville"],
    population: "3,400",
    description: "We buy houses fast for cash in Springville, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Springville sits in the Sierra Nevada foothills east of Porterville, closer to the mountains than most Tulare County communities.",
    quickFacts: [
      "Springville is an unincorporated foothill community east of Porterville, along the Tule River.",
      "The area is a gateway toward Sequoia National Forest and the Western Divide Highway.",
      "Springville's elevation and setting make it noticeably cooler than the Valley floor in summer.",
      "The community has a small-town, rural character distinct from the Highway 99 corridor cities.",
      "Springville is about a 25 minute drive from Porterville.",
    ],
  },
  {
    slug: "three-rivers",
    name: "Three Rivers",
    county: "Tulare County",
    zipCodes: ["93271"],
    neighborhoods: ["Downtown Three Rivers"],
    population: "2,000",
    description: "We buy houses fast for cash in Three Rivers, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Three Rivers sits at the entrance to Sequoia National Park, along the Kaweah River, making it one of the more tourism-driven markets House Junkies serves.",
    quickFacts: [
      "Three Rivers sits directly at the main entrance to Sequoia National Park.",
      "The community is named for the confluence of the North, Middle, and South Forks of the Kaweah River.",
      "Tourism and vacation rentals play a bigger role in the local economy here than almost anywhere else in Tulare County.",
      "Three Rivers has a small downtown with shops and restaurants catering to park visitors.",
      "The community sits roughly 25 miles east of Visalia, climbing into the foothills.",
    ],
  },
  {
    slug: "tipton",
    name: "Tipton",
    county: "Tulare County",
    zipCodes: ["93272"],
    neighborhoods: ["Downtown Tipton"],
    population: "3,000",
    description: "We buy houses fast for cash in Tipton, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Tipton is a small Highway 99 farming community south of Tulare, built almost entirely around dairy and row-crop agriculture.",
    quickFacts: [
      "Tipton sits along Highway 99 in southern Tulare County, south of the city of Tulare.",
      "The local economy is built on dairy farming and row-crop agriculture.",
      "Tipton is an unincorporated community with its own elementary school district.",
      "The community is a short drive from both Tulare and Pixley.",
      "Tipton's population has stayed small and stable, tied closely to agricultural employment.",
    ],
  },
  {
    slug: "traver",
    name: "Traver",
    county: "Tulare County",
    zipCodes: ["93673"],
    neighborhoods: ["Downtown Traver"],
    population: "700",
    description: "We buy houses fast for cash in Traver, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Traver is one of the smallest communities House Junkies serves, a historic rail-era farming settlement in northern Tulare County.",
    quickFacts: [
      "Traver is a small unincorporated community in northern Tulare County, near the Fresno County line.",
      "The settlement dates back to the late 1800s as a rail shipping point for agricultural goods.",
      "Traver's economy today is entirely agricultural, surrounded by vineyards and orchards.",
      "The community is served by the Traver Joint Elementary School District.",
      "Traver sits just off Highway 43, between Visalia and the Fresno County cities to the north.",
    ],
  },
  {
    slug: "orosi",
    name: "Orosi",
    county: "Tulare County",
    zipCodes: ["93647"],
    neighborhoods: ["Downtown Orosi"],
    population: "10,000",
    description: "We buy houses fast for cash in Orosi, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Orosi sits alongside Cutler in northern Tulare County, in one of the Valley's most concentrated citrus and grape growing areas.",
    quickFacts: [
      "Orosi is an unincorporated community in Tulare County, directly adjacent to Cutler.",
      "The area is sometimes referred to jointly as Cutler-Orosi, sharing a school district.",
      "Citrus and grape agriculture dominate the local economy.",
      "Orosi is about 20 minutes northeast of Visalia, near the Kaweah River.",
      "The community has grown steadily as a residential base for valley agricultural workers.",
    ],
  },
  {
    slug: "coalinga",
    name: "Coalinga",
    county: "Fresno County",
    zipCodes: ["93210"],
    neighborhoods: ["Downtown Coalinga"],
    population: "17,000",
    description: "We buy houses fast for cash in Coalinga, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Coalinga sits on the far west side of Fresno County, with an economy historically built on oil extraction alongside agriculture.",
    quickFacts: [
      "Coalinga is on the west side of Fresno County, along Highway 198, closer to the Coast Ranges than most Valley cities.",
      "The city's name comes from \"Coaling Station A,\" a reference to its railroad coal-refueling history.",
      "Oil production has historically been a major part of the local economy alongside agriculture.",
      "Coalinga is home to a state prison that is also a significant local employer.",
      "The city rebuilt much of its downtown after a major 1983 earthquake.",
    ],
  },
  {
    slug: "kingsburg",
    name: "Kingsburg",
    county: "Fresno County",
    zipCodes: ["93631"],
    neighborhoods: ["Downtown Kingsburg"],
    population: "13,000",
    description: "We buy houses fast for cash in Kingsburg, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Kingsburg leans into its Swedish heritage, with a Scandinavian-themed downtown that's unusual for a Central Valley farm town.",
    quickFacts: [
      "Kingsburg is in southern Fresno County, along Highway 99 between Fresno and Tulare County.",
      "The city is known for its Swedish heritage, with a water tower styled as a giant coffee pot and a Scandinavian-themed downtown.",
      "Fruit packing and row-crop agriculture anchor the local economy.",
      "Kingsburg hosts an annual Swedish Festival drawing visitors from across the Valley.",
      "The city sits close enough to both Fresno and Visalia to serve as a bedroom community for either.",
    ],
  },
  {
    slug: "parlier",
    name: "Parlier",
    county: "Fresno County",
    zipCodes: ["93648"],
    neighborhoods: ["Downtown Parlier"],
    population: "14,576",
    description: "We buy houses fast for cash in Parlier, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Parlier is one of the most agriculture-dependent cities in Fresno County, with a UC research station anchoring local crop science.",
    quickFacts: [
      "Parlier sits along Highway 99 southeast of Fresno, in the heart of the county's grape and tree-fruit region.",
      "The UC Kearney Agricultural Research and Extension Center is located just outside the city.",
      "Parlier's population has grown steadily, built almost entirely on agricultural employment.",
      "The city is one of the smaller, more affordable housing markets in Fresno County.",
      "Parlier is a short drive from both Selma and Reedley.",
    ],
  },
  {
    slug: "kettleman-city",
    name: "Kettleman City",
    county: "Kings County",
    zipCodes: ["93239"],
    neighborhoods: ["Downtown Kettleman City"],
    population: "1,350",
    description: "We buy houses fast for cash in Kettleman City, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Kettleman City sits along Interstate 5 in western Kings County, known mostly as a highway rest-stop community alongside its agricultural base.",
    quickFacts: [
      "Kettleman City is an unincorporated community at the junction of Interstate 5 and Highway 41.",
      "The community is widely known to California road-trippers for its cluster of highway restaurants and gas stations.",
      "Agriculture and oil-field work in the surrounding area support much of the local economy.",
      "Kettleman City is the westernmost community House Junkies serves in Kings County.",
      "The community sits roughly 50 miles southwest of Visalia.",
    ],
  },
  {
    slug: "madera",
    name: "Madera",
    county: "Madera County",
    zipCodes: ["93636", "93637", "93638"],
    neighborhoods: ["Downtown Madera"],
    population: "66,224",
    description: "We buy houses fast for cash in Madera, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Madera is the county seat of Madera County and one of the larger cities in the northern San Joaquin Valley.",
    quickFacts: [
      "Madera is the county seat of Madera County, incorporated in 1907.",
      "The city sits along Highway 99, just northwest of Fresno.",
      "Madera's economy spans agriculture, wine production, and growing logistics and distribution.",
      "The city has grown significantly in recent decades, now one of the larger cities in the northern San Joaquin Valley.",
      "Madera is a short drive from Yosemite National Park's western entrances.",
    ],
  },
  {
    slug: "merced",
    name: "Merced",
    county: "Merced County",
    zipCodes: ["95340", "95341", "95343"],
    neighborhoods: ["Downtown Merced"],
    population: "86,333",
    description: "We buy houses fast for cash in Merced, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Merced is the county seat of Merced County and home to the newest University of California campus, UC Merced.",
    quickFacts: [
      "Merced is the county seat of Merced County, in the northern San Joaquin Valley.",
      "UC Merced, the newest campus in the University of California system, opened in 2005 just outside the city.",
      "The city's economy spans agriculture, education, and healthcare.",
      "Merced is often called the \"Gateway to Yosemite,\" sitting along the route to the park's main entrance.",
      "Merced is one of the larger cities House Junkies serves, with a population well above most Valley cities in this report.",
    ],
  },
  {
    slug: "monterey",
    name: "Monterey",
    county: "Monterey County",
    zipCodes: ["93940", "93943"],
    neighborhoods: ["Downtown Monterey"],
    population: "30,000",
    description: "We buy houses fast for cash in Monterey, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Monterey is a coastal city on Monterey Bay, a very different housing market from the Valley cities House Junkies more typically serves inland.",
    quickFacts: [
      "Monterey sits directly on Monterey Bay, home to the Monterey Bay Aquarium and historic Cannery Row.",
      "The city's economy leans heavily on tourism, along with a significant military and government presence (the Presidio of Monterey).",
      "Monterey's housing market and home values run considerably higher than the inland Central Valley.",
      "The city was California's capital under Spanish and Mexican rule before statehood.",
      "Monterey is coastal and tourism-driven, a different kind of market than the agricultural Valley cities nearby.",
    ],
  },
  {
    slug: "san-luis-obispo",
    name: "San Luis Obispo",
    county: "San Luis Obispo County",
    zipCodes: ["93401", "93405"],
    neighborhoods: ["Downtown San Luis Obispo"],
    population: "47,000",
    description: "We buy houses fast for cash in San Luis Obispo, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "San Luis Obispo is the county seat and home to Cal Poly, a college-driven housing market on California's Central Coast.",
    quickFacts: [
      "San Luis Obispo is the county seat of San Luis Obispo County, roughly halfway between Los Angeles and San Francisco.",
      "Cal Poly San Luis Obispo is a major presence in the city, driving significant rental and student housing demand.",
      "The city's economy is built on education, tourism, and a growing tech and wine industry presence.",
      "San Luis Obispo's downtown is known for its weekly farmers market and historic mission.",
      "Coastal California housing costs here run well above the inland Central Valley.",
    ],
  },
  {
    slug: "paso-robles",
    name: "Paso Robles",
    county: "San Luis Obispo County",
    zipCodes: ["93446"],
    neighborhoods: ["Downtown Paso Robles"],
    population: "31,000",
    description: "We buy houses fast for cash in Paso Robles, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Paso Robles is one of California's major wine regions, with an economy built around vineyards and wine tourism.",
    quickFacts: [
      "Paso Robles sits along Highway 101 in northern San Luis Obispo County.",
      "The area is one of California's most prominent wine-growing regions, with hundreds of wineries nearby.",
      "The city hosts the California Mid-State Fair, a major regional event each summer.",
      "Paso Robles has a historic downtown built around a central park.",
      "Agriculture here is dominated by vineyards rather than the row crops typical of the Central Valley.",
    ],
  },
  {
    slug: "pismo-beach",
    name: "Pismo Beach",
    county: "San Luis Obispo County",
    zipCodes: ["93449"],
    neighborhoods: ["Downtown Pismo Beach"],
    population: "8,000",
    description: "We buy houses fast for cash in Pismo Beach, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Pismo Beach is a coastal tourist town known for its beach, pier, and dunes, a very different market from the Valley's inland cities.",
    quickFacts: [
      "Pismo Beach sits directly on the California coast in southern San Luis Obispo County.",
      "The city is known for its pier, sand dunes, and as a classic California beach-town destination.",
      "Tourism is the backbone of the local economy, with hotels and vacation rentals a major share of housing stock.",
      "Pismo Beach is part of the \"Five Cities\" area along with Grover Beach, Arroyo Grande, and others.",
      "Coastal property values here run far above the inland Central Valley.",
    ],
  },
  {
    slug: "grover-beach",
    name: "Grover Beach",
    county: "San Luis Obispo County",
    zipCodes: ["93433"],
    neighborhoods: ["Downtown Grover Beach"],
    population: "13,000",
    description: "We buy houses fast for cash in Grover Beach, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Grover Beach is a small coastal city in the \"Five Cities\" area of southern San Luis Obispo County.",
    quickFacts: [
      "Grover Beach sits just south of Pismo Beach on California's Central Coast.",
      "The city is part of the \"Five Cities\" area, along with Arroyo Grande, Pismo Beach, Oceano, and Shell Beach.",
      "Tourism and coastal recreation play a large role in the local economy.",
      "Grover Beach has a more residential, year-round community feel than its tourist-heavy neighbor Pismo Beach.",
      "The city sits along Highway 1, a short drive from Pismo Beach's pier and dunes.",
    ],
  },
  {
    slug: "avila-beach",
    name: "Avila Beach",
    county: "San Luis Obispo County",
    zipCodes: ["93424"],
    neighborhoods: ["Downtown Avila Beach"],
    population: "1,500",
    description: "We buy houses fast for cash in Avila Beach, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Avila Beach is a small, sheltered beach community in San Luis Obispo County, one of the smallest markets House Junkies serves.",
    quickFacts: [
      "Avila Beach is an unincorporated coastal community in San Luis Obispo County.",
      "The town sits on a sheltered cove, making its beach notably calmer than much of the surrounding coastline.",
      "Tourism, hot springs resorts, and a small marina anchor the local economy.",
      "Avila Beach was substantially rebuilt in the early 2000s following an underground oil contamination cleanup.",
      "It's one of the smallest and most tourism-dependent communities House Junkies serves.",
    ],
  },
  {
    slug: "bishop",
    name: "Bishop",
    county: "Inyo County",
    zipCodes: ["93514"],
    neighborhoods: ["Downtown Bishop"],
    population: "3,800",
    description: "We buy houses fast for cash in Bishop, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Bishop is the largest city in Inyo County and the main commercial hub for the Eastern Sierra, a long drive and a very different market from the Valley cities House Junkies more typically serves.",
    quickFacts: [
      "Bishop is the only incorporated city in Inyo County, on the east side of the Sierra Nevada.",
      "The city serves as the main commercial center for the Eastern Sierra, including nearby Mammoth Lakes.",
      "Outdoor recreation and tourism, fishing, climbing, and access to the Sierra, drive much of the local economy.",
      "Bishop sits along Highway 395, a very different route and region from the Highway 99 Central Valley corridor.",
      "The Owens Valley setting makes Bishop's climate and geography distinct from the rest of House Junkies' service area.",
    ],
  },
  {
    slug: "hollister",
    name: "Hollister",
    county: "San Benito County",
    zipCodes: ["95023"],
    neighborhoods: ["Downtown Hollister"],
    population: "37,000",
    description: "We buy houses fast for cash in Hollister, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Hollister is the county seat of San Benito County, a smaller city between the Central Valley and the Bay Area known for its agricultural roots and motorcycle rally history.",
    quickFacts: [
      "Hollister is the county seat of San Benito County, southeast of the greater Bay Area.",
      "The city has historically been known for the annual Hollister Independence Rally, a motorcycle gathering.",
      "Agriculture, particularly row crops and ranching, remains central to the surrounding economy.",
      "Hollister has grown as a more affordable alternative within commuting range of Silicon Valley and the Bay Area.",
      "The city's setting, between the Gabilan Range and the Diablo Range, is distinct from the flat Central Valley floor.",
    ],
  },
  {
    slug: "chowchilla",
    name: "Chowchilla",
    county: "Madera County",
    zipCodes: ["93610"],
    neighborhoods: ["Downtown Chowchilla"],
    population: "19,169",
    description: "We buy houses fast for cash in Chowchilla, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Chowchilla sits along Highway 99 at the northern edge of the San Joaquin Valley, straddling the Madera/Merced county line.",
    quickFacts: [
      "Chowchilla is an incorporated city at the Madera/Merced county line, along Highway 99.",
      "The city's economy is built on agriculture, dairy, and food processing.",
      "Chowchilla is home to two California state prisons for women, significant local employers.",
      "The city gained national attention in 1976 as the site of a notorious school bus kidnapping.",
      "Chowchilla has grown steadily, roughly tripling in population since 1990.",
    ],
  },
  {
    slug: "madera-ranchos",
    name: "Madera Ranchos",
    county: "Madera County",
    zipCodes: ["93636"],
    neighborhoods: ["Madera Ranchos"],
    population: "3,623",
    description: "We buy houses fast for cash in Madera Ranchos, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Madera Ranchos is a rural-residential community just north of the city of Madera, known for larger lots than the city proper.",
    quickFacts: [
      "Madera Ranchos is an unincorporated community directly north of the city of Madera.",
      "Properties here tend to sit on larger rural-residential lots compared to in-town Madera.",
      "The community shares a zip code and much of its services with the city of Madera.",
      "Agriculture surrounds much of Madera Ranchos, consistent with the broader county.",
      "The area functions largely as a residential community for people working in and around Madera.",
    ],
  },
  {
    slug: "yosemite-lakes",
    name: "Yosemite Lakes",
    county: "Madera County",
    zipCodes: ["93644"],
    neighborhoods: ["Yosemite Lakes"],
    population: "5,022",
    description: "We buy houses fast for cash in Yosemite Lakes, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Yosemite Lakes sits in the Sierra foothills of Madera County, closer to Yosemite National Park than to the Valley floor.",
    quickFacts: [
      "Yosemite Lakes is an unincorporated foothill community in Madera County, near Coarsegold.",
      "The area sits along Highway 41, the main route between Fresno and Yosemite National Park's south entrance.",
      "Housing stock here tends toward larger wooded lots, distinct from the Valley floor cities.",
      "Tourism traffic headed to Yosemite passes directly through the area.",
      "The community's elevation makes it noticeably cooler than Madera or Fresno in summer.",
    ],
  },
  {
    slug: "oakhurst",
    name: "Oakhurst",
    county: "Madera County",
    zipCodes: ["93644"],
    neighborhoods: ["Downtown Oakhurst"],
    population: "5,945",
    description: "We buy houses fast for cash in Oakhurst, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Oakhurst is the main gateway town to Yosemite National Park's south entrance, with over a million park visitors passing through on Highway 41 each year.",
    quickFacts: [
      "Oakhurst sits along Highway 41, the primary route to Yosemite National Park's south entrance.",
      "Formerly known as Fresno Flats, the town has served travelers heading to Yosemite since the 1870s.",
      "Tourism tied to Yosemite is a major part of the local economy, alongside Sierra foothill living.",
      "Oakhurst's elevation and forested setting make it noticeably cooler than the Valley floor.",
      "The community serves as the commercial hub for the surrounding Sierra foothill towns in eastern Madera County.",
    ],
  },
  {
    slug: "los-banos",
    name: "Los Banos",
    county: "Merced County",
    zipCodes: ["93635"],
    neighborhoods: ["Downtown Los Banos"],
    population: "40,571",
    description: "We buy houses fast for cash in Los Banos, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Los Banos is the second-largest city in Merced County and a growing bedroom community along the Highway 152 corridor toward the Bay Area.",
    quickFacts: [
      "Los Banos sits along Highway 152, a major route connecting the Valley to the Bay Area over Pacheco Pass.",
      "The city has grown significantly as commuters look for more affordable housing within range of Silicon Valley.",
      "Agriculture, particularly dairy and row crops, remains central to the surrounding economy.",
      "The San Luis Reservoir, one of California's largest, sits just west of the city.",
      "Los Banos is the county seat alternative commercial hub alongside Merced itself.",
    ],
  },
  {
    slug: "atwater",
    name: "Atwater",
    county: "Merced County",
    zipCodes: ["95301"],
    neighborhoods: ["Downtown Atwater"],
    population: "30,296",
    description: "We buy houses fast for cash in Atwater, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Atwater sits just northwest of the city of Merced, with a local economy historically tied to the former Castle Air Force Base.",
    quickFacts: [
      "Atwater is directly adjacent to the city of Merced, along Highway 99.",
      "The former Castle Air Force Base, now home to the Castle Air Museum, sits just outside the city.",
      "Agriculture and logistics both play a role in the local economy today.",
      "Atwater's population has grown steadily as a more affordable alternative to Merced proper.",
      "The city is close enough to Merced to function as part of the same housing market.",
    ],
  },
  {
    slug: "livingston",
    name: "Livingston",
    county: "Merced County",
    zipCodes: ["95334"],
    neighborhoods: ["Downtown Livingston"],
    population: "14,926",
    description: "We buy houses fast for cash in Livingston, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Livingston sits along Highway 99 between Merced and Turlock, with an economy built on dairy and food processing.",
    quickFacts: [
      "Livingston is along Highway 99 in northern Merced County, between Merced and Turlock.",
      "The city is home to a large poultry processing plant, a major local employer.",
      "Dairy farming surrounds much of the city, typical of this stretch of the Valley.",
      "Livingston has a sizeable Sikh community and temple reflecting the area's agricultural labor history.",
      "The city sits close enough to Merced to share much of its commercial and housing market.",
    ],
  },
  {
    slug: "gustine",
    name: "Gustine",
    county: "Merced County",
    zipCodes: ["95322"],
    neighborhoods: ["Downtown Gustine"],
    population: "5,709",
    description: "We buy houses fast for cash in Gustine, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Gustine is a small dairy-farming town in western Merced County, one of the smaller communities in House Junkies' expanded service area.",
    quickFacts: [
      "Gustine sits in western Merced County, closer to the Coast Ranges than to Highway 99.",
      "The local economy is built almost entirely on dairy and cattle ranching.",
      "The city calls itself the \"Dairyland of the Nation\" for its concentration of dairies.",
      "Gustine has a small, tight-knit downtown typical of western San Joaquin Valley farm towns.",
      "The community sits along the route between Los Banos and the Interstate 5 corridor.",
    ],
  },
  {
    slug: "salinas",
    name: "Salinas",
    county: "Monterey County",
    zipCodes: ["93901", "93905", "93906"],
    neighborhoods: ["Downtown Salinas", "Alisal"],
    population: "160,000",
    description: "We buy houses fast for cash in Salinas, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Salinas is the largest city in Monterey County and the county seat, known as the \"Salad Bowl of the World\" for its produce industry.",
    quickFacts: [
      "Salinas is the county seat and largest city in Monterey County.",
      "The surrounding Salinas Valley is one of the most productive produce-growing regions in the world.",
      "Author John Steinbeck was born in Salinas, and the National Steinbeck Center is located downtown.",
      "Salinas sits inland from the coast, with a housing market distinct from Monterey or Carmel.",
      "Agriculture, both growing and food processing and distribution, anchors the local economy.",
    ],
  },
  {
    slug: "carmel",
    name: "Carmel-by-the-Sea",
    county: "Monterey County",
    zipCodes: ["93921", "93923"],
    neighborhoods: ["Downtown Carmel"],
    population: "3,220",
    description: "We buy houses fast for cash in Carmel-by-the-Sea, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Carmel-by-the-Sea is one of the smallest and most expensive housing markets House Junkies' service area touches, a famous coastal village known for its cottages and art galleries.",
    quickFacts: [
      "Carmel-by-the-Sea is a small, incorporated coastal city known for its cottage-style architecture and art galleries.",
      "The city famously has no residential mail delivery and no street addresses on many homes.",
      "Clint Eastwood served as the city's mayor in the 1980s.",
      "Carmel's housing market runs far above the inland Central Valley in value.",
      "The city sits along the Monterey Peninsula, adjacent to Pebble Beach and the Carmel Valley.",
    ],
  },
  {
    slug: "seaside",
    name: "Seaside",
    county: "Monterey County",
    zipCodes: ["93955"],
    neighborhoods: ["Downtown Seaside"],
    population: "32,366",
    description: "We buy houses fast for cash in Seaside, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Seaside is the most populous city on the Monterey Peninsula, historically tied to the former Fort Ord military base.",
    quickFacts: [
      "Seaside sits on the Monterey Peninsula, adjacent to the city of Monterey.",
      "Much of the city was built on and around the former Fort Ord Army base, closed in the 1990s.",
      "California State University, Monterey Bay now occupies part of the former base land.",
      "Seaside offers relatively more affordable housing than Monterey or Carmel on the same peninsula.",
      "The city's population is more residential and working-class than its tourist-oriented neighbors.",
    ],
  },
  {
    slug: "marina",
    name: "Marina",
    county: "Monterey County",
    zipCodes: ["93933"],
    neighborhoods: ["Downtown Marina"],
    population: "27,197",
    description: "We buy houses fast for cash in Marina, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Marina sits on the north end of the Monterey Peninsula, with newer housing stock than many of its coastal neighbors.",
    quickFacts: [
      "Marina sits at the northern end of Monterey Bay, along Highway 1.",
      "The city includes part of the former Fort Ord Army base, redeveloped into housing and open space.",
      "CSU Monterey Bay's main campus sits partly within Marina's boundaries.",
      "Marina's housing stock is generally newer than Monterey or Pacific Grove.",
      "The city sits along the Monterey Bay National Marine Sanctuary coastline.",
    ],
  },
  {
    slug: "big-pine",
    name: "Big Pine",
    county: "Inyo County",
    zipCodes: ["93513"],
    neighborhoods: ["Big Pine"],
    population: "1,875",
    description: "We buy houses fast for cash in Big Pine, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Big Pine sits in the Owens Valley between Bishop and Lone Pine, home to the Big Pine Paiute Tribe.",
    quickFacts: [
      "Big Pine is an unincorporated community in the Owens Valley, along Highway 395.",
      "The Big Pine Paiute Tribe of the Owens Valley has its headquarters here.",
      "The community sits at the base of some of the tallest peaks in the contiguous US, including White Mountain.",
      "Outdoor recreation, fishing, and access to the Eastern Sierra draw visitors through the area.",
      "Big Pine is roughly 15 miles south of Bishop, the largest town in Inyo County.",
    ],
  },
  {
    slug: "independence",
    name: "Independence",
    county: "Inyo County",
    zipCodes: ["93526"],
    neighborhoods: ["Independence"],
    population: "593",
    description: "We buy houses fast for cash in Independence, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Independence is the county seat of Inyo County despite its small size, and sits near the historic Manzanar National Historic Site.",
    quickFacts: [
      "Independence is the county seat of Inyo County, despite being one of its smallest communities.",
      "Manzanar National Historic Site, a former WWII Japanese-American incarceration camp, sits just south of town.",
      "The community sits along Highway 395 in the Owens Valley, between Big Pine and Lone Pine.",
      "Independence is a small, historic town with a 19th-century county courthouse.",
      "Eastern Sierra outdoor recreation drives much of the seasonal visitor traffic through the area.",
    ],
  },
  {
    slug: "lone-pine",
    name: "Lone Pine",
    county: "Inyo County",
    zipCodes: ["93545"],
    neighborhoods: ["Lone Pine"],
    population: "2,014",
    description: "We buy houses fast for cash in Lone Pine, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Lone Pine sits at the base of Mount Whitney, the tallest peak in the contiguous United States, and is a well-known filming location for Western movies.",
    quickFacts: [
      "Lone Pine sits directly below Mount Whitney, the highest peak in the contiguous United States.",
      "The surrounding Alabama Hills have served as a filming location for countless Western movies and TV shows.",
      "The town serves as a gateway for hikers heading to Mount Whitney and the Eastern Sierra backcountry.",
      "Tourism and outdoor recreation anchor much of the local economy.",
      "Lone Pine sits along Highway 395, about 16 miles south of Independence.",
    ],
  },
  {
    slug: "shoshone",
    name: "Shoshone",
    county: "Inyo County",
    zipCodes: ["92384"],
    neighborhoods: ["Shoshone"],
    population: "22",
    description: "We buy houses fast for cash in Shoshone, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Shoshone is a tiny desert community near the California/Nevada border, a waypoint for travelers heading into Death Valley.",
    quickFacts: [
      "Shoshone is one of the smallest communities House Junkies serves, with a population in the dozens.",
      "The community sits near the eastern edge of Inyo County, close to the Nevada border.",
      "Shoshone is a well-known waypoint for travelers entering Death Valley National Park from the east.",
      "A natural spring-fed wetland and small museum anchor the tiny town's identity.",
      "Given its size, real estate activity here is naturally limited compared to larger Inyo County towns.",
    ],
  },
  {
    slug: "san-juan-bautista",
    name: "San Juan Bautista",
    county: "San Benito County",
    zipCodes: ["95045"],
    neighborhoods: ["Downtown San Juan Bautista"],
    population: "2,124",
    description: "We buy houses fast for cash in San Juan Bautista, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "San Juan Bautista is a small historic city built around one of California's best-preserved Spanish missions.",
    quickFacts: [
      "San Juan Bautista is home to Mission San Juan Bautista, one of California's largest and best-preserved missions.",
      "The city's historic downtown and plaza are part of San Juan Bautista State Historic Park.",
      "The San Andreas Fault runs directly beneath part of the town.",
      "San Juan Bautista sits a short drive from both Hollister and Gilroy.",
      "Tourism tied to the mission and historic district plays a real role in the local economy.",
    ],
  },
  {
    slug: "tres-pinos",
    name: "Tres Pinos",
    county: "San Benito County",
    zipCodes: ["95075"],
    neighborhoods: ["Tres Pinos"],
    population: "443",
    description: "We buy houses fast for cash in Tres Pinos, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Tres Pinos is a small unincorporated community just south of Hollister, home to the county fairgrounds.",
    quickFacts: [
      "Tres Pinos sits along State Route 25, about 4 miles south of Hollister.",
      "Bolado Park, located in Tres Pinos, hosts the San Benito County Fair and rodeo.",
      "The community's economy is tied closely to the surrounding ranching and agricultural land.",
      "Tres Pinos is one of the smaller, more rural communities in House Junkies' San Benito County coverage.",
      "The town has its own elementary school district serving the surrounding area.",
    ],
  },
  {
    slug: "ridgemark",
    name: "Ridgemark",
    county: "San Benito County",
    zipCodes: ["95023"],
    neighborhoods: ["Ridgemark"],
    population: "3,212",
    description: "We buy houses fast for cash in Ridgemark, CA. As-is, any condition, no fees, no repairs.",
    marketNote: "Ridgemark is a residential community just south of Hollister, built around a golf course and country club.",
    quickFacts: [
      "Ridgemark is an unincorporated community directly adjacent to Hollister.",
      "The community developed around the Ridgemark Golf & Country Club.",
      "Housing here tends to be newer and more suburban than central Hollister.",
      "Ridgemark shares a zip code and much of its infrastructure with Hollister.",
      "The community functions as a residential extension of the Hollister housing market.",
    ],
  },
];

export function getCity(slug: string): CityData | undefined {
  return cities.find((c) => c.slug === slug);
}
